# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-18 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estanteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='objeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreO', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerounidades', models.IntegerField()),
                ('estanteria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.estanteria')),
                ('objeto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.objeto')),
            ],
        ),
    ]
